// Copyright 2026 Cloudfra
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Wire contract for the ffmpegembed library. Every public argument and result
// type is defined here so that inputs and outputs are always structured, and so
// that the same shapes can be serialized (JSON / binary) across language
// boundaries. Go types are generated from this file (see ffrun.pb.go).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/ffrun.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// High-level lifecycle states of an Ffmpeg run.
type FfmpegState int32

const (
	FfmpegState_FFMPEG_STATE_UNSPECIFIED FfmpegState = 0
	FfmpegState_FFMPEG_STATE_STARTING    FfmpegState = 1
	FfmpegState_FFMPEG_STATE_RUNNING     FfmpegState = 2
	FfmpegState_FFMPEG_STATE_COMPLETED   FfmpegState = 3
	FfmpegState_FFMPEG_STATE_FAILED      FfmpegState = 4
)

// Enum value maps for FfmpegState.
var (
	FfmpegState_name = map[int32]string{
		0: "FFMPEG_STATE_UNSPECIFIED",
		1: "FFMPEG_STATE_STARTING",
		2: "FFMPEG_STATE_RUNNING",
		3: "FFMPEG_STATE_COMPLETED",
		4: "FFMPEG_STATE_FAILED",
	}
	FfmpegState_value = map[string]int32{
		"FFMPEG_STATE_UNSPECIFIED": 0,
		"FFMPEG_STATE_STARTING":    1,
		"FFMPEG_STATE_RUNNING":     2,
		"FFMPEG_STATE_COMPLETED":   3,
		"FFMPEG_STATE_FAILED":      4,
	}
)

func (x FfmpegState) Enum() *FfmpegState {
	p := new(FfmpegState)
	*p = x
	return p
}

func (x FfmpegState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FfmpegState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ffrun_proto_enumTypes[0].Descriptor()
}

func (FfmpegState) Type() protoreflect.EnumType {
	return &file_proto_ffrun_proto_enumTypes[0]
}

func (x FfmpegState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FfmpegState.Descriptor instead.
func (FfmpegState) EnumDescriptor() ([]byte, []int) {
	return file_proto_ffrun_proto_rawDescGZIP(), []int{0}
}

// Args configures how New resolves the ffmpeg/ffprobe executables.
type Args struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prefer a ffmpeg/ffprobe found on the system PATH over the embedded copies.
	// When false (default) the embedded binaries are used when this build has
	// them, and the system PATH is only consulted when it does not.
	UseExternalIfAvailable bool `protobuf:"varint,1,opt,name=use_external_if_available,json=useExternalIfAvailable,proto3" json:"use_external_if_available,omitempty"`
	// Inline binary override. When non-empty these bytes are used verbatim and
	// written to a temp dir, taking precedence over both the embedded binary and
	// the system PATH.
	FfmpegBinary  []byte `protobuf:"bytes,2,opt,name=ffmpeg_binary,json=ffmpegBinary,proto3" json:"ffmpeg_binary,omitempty"`
	FfprobeBinary []byte `protobuf:"bytes,3,opt,name=ffprobe_binary,json=ffprobeBinary,proto3" json:"ffprobe_binary,omitempty"`
	// Directory to extract the embedded binaries into. When empty a fresh temp
	// dir is created. When set, Close() will NOT remove it.
	WorkDir string `protobuf:"bytes,4,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	// Never download ffmpeg/ffprobe. By default, when there is neither an
	// embedded binary for the platform nor one on the system PATH, a pinned,
	// checksum-verified static build is downloaded and cached. Leaving this
	// false therefore accepts the license of that build (GPL-3.0-or-later);
	// set it to true to refuse both the download and that license, in which
	// case New fails with ErrNoBinary instead.
	DisableDownload bool `protobuf:"varint,5,opt,name=disable_download,json=disableDownload,proto3" json:"disable_download,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Args) Reset() {
	*x = Args{}
	mi := &file_proto_ffrun_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Args) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Args) ProtoMessage() {}

func (x *Args) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffrun_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Args.ProtoReflect.Descriptor instead.
func (*Args) Descriptor() ([]byte, []int) {
	return file_proto_ffrun_proto_rawDescGZIP(), []int{0}
}

func (x *Args) GetUseExternalIfAvailable() bool {
	if x != nil {
		return x.UseExternalIfAvailable
	}
	return false
}

func (x *Args) GetFfmpegBinary() []byte {
	if x != nil {
		return x.FfmpegBinary
	}
	return nil
}

func (x *Args) GetFfprobeBinary() []byte {
	if x != nil {
		return x.FfprobeBinary
	}
	return nil
}

func (x *Args) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *Args) GetDisableDownload() bool {
	if x != nil {
		return x.DisableDownload
	}
	return false
}

// FfProbeArgs configures an Ffprobe call. Either set the structured fields or
// supply raw_args (both are accepted; raw_args are appended last).
type FfProbeArgs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Input media file to probe.
	Input string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	// Include container/format metadata (default true).
	ShowFormat bool `protobuf:"varint,2,opt,name=show_format,json=showFormat,proto3" json:"show_format,omitempty"`
	// Include per-stream metadata (default true).
	ShowStreams bool `protobuf:"varint,3,opt,name=show_streams,json=showStreams,proto3" json:"show_streams,omitempty"`
	// Include chapter metadata.
	ShowChapters bool `protobuf:"varint,4,opt,name=show_chapters,json=showChapters,proto3" json:"show_chapters,omitempty"`
	// Include per-frame metadata (may be large).
	ShowFrames bool `protobuf:"varint,5,opt,name=show_frames,json=showFrames,proto3" json:"show_frames,omitempty"`
	// Only report the matching stream, e.g. "v:0" or "a:1".
	SelectStreams string `protobuf:"bytes,6,opt,name=select_streams,json=selectStreams,proto3" json:"select_streams,omitempty"`
	// Output format: "json" (default), "compact", or "default".
	PrintFormat string `protobuf:"bytes,7,opt,name=print_format,json=printFormat,proto3" json:"print_format,omitempty"`
	// Arbitrary additional ffprobe arguments, appended after the structured ones.
	RawArgs       []string `protobuf:"bytes,8,rep,name=raw_args,json=rawArgs,proto3" json:"raw_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FfProbeArgs) Reset() {
	*x = FfProbeArgs{}
	mi := &file_proto_ffrun_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FfProbeArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FfProbeArgs) ProtoMessage() {}

func (x *FfProbeArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffrun_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FfProbeArgs.ProtoReflect.Descriptor instead.
func (*FfProbeArgs) Descriptor() ([]byte, []int) {
	return file_proto_ffrun_proto_rawDescGZIP(), []int{1}
}

func (x *FfProbeArgs) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *FfProbeArgs) GetShowFormat() bool {
	if x != nil {
		return x.ShowFormat
	}
	return false
}

func (x *FfProbeArgs) GetShowStreams() bool {
	if x != nil {
		return x.ShowStreams
	}
	return false
}

func (x *FfProbeArgs) GetShowChapters() bool {
	if x != nil {
		return x.ShowChapters
	}
	return false
}

func (x *FfProbeArgs) GetShowFrames() bool {
	if x != nil {
		return x.ShowFrames
	}
	return false
}

func (x *FfProbeArgs) GetSelectStreams() string {
	if x != nil {
		return x.SelectStreams
	}
	return ""
}

func (x *FfProbeArgs) GetPrintFormat() string {
	if x != nil {
		return x.PrintFormat
	}
	return ""
}

func (x *FfProbeArgs) GetRawArgs() []string {
	if x != nil {
		return x.RawArgs
	}
	return nil
}

// A single codec stream as reported by ffprobe.
type FfProbeStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Numeric stream index (or "index" string from ffprobe).
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	// E.g. "h264", "aac", "pcm_s16le".
	CodecName string `protobuf:"bytes,2,opt,name=codec_name,json=codecName,proto3" json:"codec_name,omitempty"`
	// Long codec description.
	CodecLongName string `protobuf:"bytes,3,opt,name=codec_long_name,json=codecLongName,proto3" json:"codec_long_name,omitempty"`
	// E.g. "High" for h264.
	Profile string `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	// audio | video | subtitle | data | attachment
	CodecType string `protobuf:"bytes,5,opt,name=codec_type,json=codecType,proto3" json:"codec_type,omitempty"`
	// 0x00000000 style tag.
	CodecTag string `protobuf:"bytes,6,opt,name=codec_tag,json=codecTag,proto3" json:"codec_tag,omitempty"`
	// Human-readable tag, e.g. "mp4a".
	CodecTagString string `protobuf:"bytes,7,opt,name=codec_tag_string,json=codecTagString,proto3" json:"codec_tag_string,omitempty"`
	// Bits per second (0 when unknown).
	BitRate int64 `protobuf:"varint,8,opt,name=bit_rate,json=bitRate,proto3" json:"bit_rate,omitempty"`
	// Video: coded / natural width.
	Width int32 `protobuf:"varint,9,opt,name=width,proto3" json:"width,omitempty"`
	// Video: coded / natural height.
	Height int32 `protobuf:"varint,10,opt,name=height,proto3" json:"height,omitempty"`
	// Video pixel format, e.g. "yuv420p".
	PixFmt string `protobuf:"bytes,11,opt,name=pix_fmt,json=pixFmt,proto3" json:"pix_fmt,omitempty"`
	// Codec level, e.g. "40".
	Level string `protobuf:"bytes,12,opt,name=level,proto3" json:"level,omitempty"`
	// Real base framerate (e.g. 30, 24).
	RFrameRate float64 `protobuf:"fixed64,13,opt,name=r_frame_rate,json=rFrameRate,proto3" json:"r_frame_rate,omitempty"`
	// Average framerate.
	AvgFrameRate float64 `protobuf:"fixed64,14,opt,name=avg_frame_rate,json=avgFrameRate,proto3" json:"avg_frame_rate,omitempty"`
	// Audio: sample rate in Hz.
	SampleRate int64 `protobuf:"varint,15,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	// Audio: channel count.
	Channels int32 `protobuf:"varint,16,opt,name=channels,proto3" json:"channels,omitempty"`
	// Audio: "stereo", "mono", ...
	ChannelLayout string `protobuf:"bytes,17,opt,name=channel_layout,json=channelLayout,proto3" json:"channel_layout,omitempty"`
	// Audio: integer bits per sample.
	BitsPerSample int32 `protobuf:"varint,18,opt,name=bits_per_sample,json=bitsPerSample,proto3" json:"bits_per_sample,omitempty"`
	// Decoder/codec settings blob (key=value;...).
	Settings string `protobuf:"bytes,19,opt,name=settings,proto3" json:"settings,omitempty"`
	// Arbitrary tags from ffprobe (title, language, ...).
	Tags map[string]string `protobuf:"bytes,20,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The raw JSON object ffprobe emitted for this stream (full fidelity).
	RawJson       string `protobuf:"bytes,21,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FfProbeStream) Reset() {
	*x = FfProbeStream{}
	mi := &file_proto_ffrun_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FfProbeStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FfProbeStream) ProtoMessage() {}

func (x *FfProbeStream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffrun_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FfProbeStream.ProtoReflect.Descriptor instead.
func (*FfProbeStream) Descriptor() ([]byte, []int) {
	return file_proto_ffrun_proto_rawDescGZIP(), []int{2}
}

func (x *FfProbeStream) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *FfProbeStream) GetCodecName() string {
	if x != nil {
		return x.CodecName
	}
	return ""
}

func (x *FfProbeStream) GetCodecLongName() string {
	if x != nil {
		return x.CodecLongName
	}
	return ""
}

func (x *FfProbeStream) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *FfProbeStream) GetCodecType() string {
	if x != nil {
		return x.CodecType
	}
	return ""
}

func (x *FfProbeStream) GetCodecTag() string {
	if x != nil {
		return x.CodecTag
	}
	return ""
}

func (x *FfProbeStream) GetCodecTagString() string {
	if x != nil {
		return x.CodecTagString
	}
	return ""
}

func (x *FfProbeStream) GetBitRate() int64 {
	if x != nil {
		return x.BitRate
	}
	return 0
}

func (x *FfProbeStream) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FfProbeStream) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FfProbeStream) GetPixFmt() string {
	if x != nil {
		return x.PixFmt
	}
	return ""
}

func (x *FfProbeStream) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *FfProbeStream) GetRFrameRate() float64 {
	if x != nil {
		return x.RFrameRate
	}
	return 0
}

func (x *FfProbeStream) GetAvgFrameRate() float64 {
	if x != nil {
		return x.AvgFrameRate
	}
	return 0
}

func (x *FfProbeStream) GetSampleRate() int64 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *FfProbeStream) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *FfProbeStream) GetChannelLayout() string {
	if x != nil {
		return x.ChannelLayout
	}
	return ""
}

func (x *FfProbeStream) GetBitsPerSample() int32 {
	if x != nil {
		return x.BitsPerSample
	}
	return 0
}

func (x *FfProbeStream) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

func (x *FfProbeStream) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FfProbeStream) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

// Container / format metadata as reported by ffprobe.
type FfProbeFormat struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Filename string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	// File size in bytes.
	FileSize int64 `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	// E.g. "mov,mp4,m4a,3gp,3g2,mj2".
	FormatName string `protobuf:"bytes,3,opt,name=format_name,json=formatName,proto3" json:"format_name,omitempty"`
	// Long name, e.g. "QuickTime / MOV".
	FormatLongName string `protobuf:"bytes,4,opt,name=format_long_name,json=formatLongName,proto3" json:"format_long_name,omitempty"`
	// Start time, seconds.
	StartTime float64 `protobuf:"fixed64,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Duration, seconds.
	Duration float64 `protobuf:"fixed64,6,opt,name=duration,proto3" json:"duration,omitempty"`
	// Bits per second (0 when unknown).
	BitRate int64 `protobuf:"varint,7,opt,name=bit_rate,json=bitRate,proto3" json:"bit_rate,omitempty"`
	// Arbitrary tags from ffprobe.
	Tags map[string]string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The raw JSON object ffprobe emitted for the format (full fidelity).
	RawJson       string `protobuf:"bytes,9,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FfProbeFormat) Reset() {
	*x = FfProbeFormat{}
	mi := &file_proto_ffrun_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FfProbeFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FfProbeFormat) ProtoMessage() {}

func (x *FfProbeFormat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffrun_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FfProbeFormat.ProtoReflect.Descriptor instead.
func (*FfProbeFormat) Descriptor() ([]byte, []int) {
	return file_proto_ffrun_proto_rawDescGZIP(), []int{3}
}

func (x *FfProbeFormat) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FfProbeFormat) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FfProbeFormat) GetFormatName() string {
	if x != nil {
		return x.FormatName
	}
	return ""
}

func (x *FfProbeFormat) GetFormatLongName() string {
	if x != nil {
		return x.FormatLongName
	}
	return ""
}

func (x *FfProbeFormat) GetStartTime() float64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *FfProbeFormat) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *FfProbeFormat) GetBitRate() int64 {
	if x != nil {
		return x.BitRate
	}
	return 0
}

func (x *FfProbeFormat) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FfProbeFormat) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

// FfProbeResult is the structured outcome of Ffprobe.
type FfProbeResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Present when show_format was true.
	Format *FfProbeFormat `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	// One entry per stream (when show_streams was true).
	Streams []*FfProbeStream `protobuf:"bytes,2,rep,name=streams,proto3" json:"streams,omitempty"`
	// The entire raw ffprobe JSON, for consumers that want the full payload.
	RawJson       string `protobuf:"bytes,3,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FfProbeResult) Reset() {
	*x = FfProbeResult{}
	mi := &file_proto_ffrun_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FfProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FfProbeResult) ProtoMessage() {}

func (x *FfProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffrun_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FfProbeResult.ProtoReflect.Descriptor instead.
func (*FfProbeResult) Descriptor() ([]byte, []int) {
	return file_proto_ffrun_proto_rawDescGZIP(), []int{4}
}

func (x *FfProbeResult) GetFormat() *FfProbeFormat {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *FfProbeResult) GetStreams() []*FfProbeStream {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *FfProbeResult) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

// FfmpegArgs configures an Ffmpeg run. Either populate the structured fields or
// supply raw_args (both are accepted; raw_args are appended last).
type FfmpegArgs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Input media files.
	Inputs []string `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// Output media file.
	Output string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	// Video codec (e.g. "libx264"), emitted as -c:v.
	VideoCodec string `protobuf:"bytes,3,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"`
	// Audio codec (e.g. "aac"), emitted as -c:a.
	AudioCodec string `protobuf:"bytes,4,opt,name=audio_codec,json=audioCodec,proto3" json:"audio_codec,omitempty"`
	// Constant rate factor; when > 0 emitted as -crf.
	Crf int32 `protobuf:"varint,5,opt,name=crf,proto3" json:"crf,omitempty"`
	// Encoder preset (e.g. "veryfast"), emitted as -preset.
	Preset string `protobuf:"bytes,6,opt,name=preset,proto3" json:"preset,omitempty"`
	// Bitrate (e.g. "128k"), emitted as -b.
	Bitrate string `protobuf:"bytes,7,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	// Add -movflags +faststart (MP4 / MOV).
	Faststart bool `protobuf:"varint,8,opt,name=faststart,proto3" json:"faststart,omitempty"`
	// When true (default) add -y to overwrite without prompting.
	Overwrite bool `protobuf:"varint,9,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	// Arbitrary additional ffmpeg arguments, appended after the structured ones.
	RawArgs       []string `protobuf:"bytes,10,rep,name=raw_args,json=rawArgs,proto3" json:"raw_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FfmpegArgs) Reset() {
	*x = FfmpegArgs{}
	mi := &file_proto_ffrun_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FfmpegArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FfmpegArgs) ProtoMessage() {}

func (x *FfmpegArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffrun_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FfmpegArgs.ProtoReflect.Descriptor instead.
func (*FfmpegArgs) Descriptor() ([]byte, []int) {
	return file_proto_ffrun_proto_rawDescGZIP(), []int{5}
}

func (x *FfmpegArgs) GetInputs() []string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *FfmpegArgs) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *FfmpegArgs) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

func (x *FfmpegArgs) GetAudioCodec() string {
	if x != nil {
		return x.AudioCodec
	}
	return ""
}

func (x *FfmpegArgs) GetCrf() int32 {
	if x != nil {
		return x.Crf
	}
	return 0
}

func (x *FfmpegArgs) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *FfmpegArgs) GetBitrate() string {
	if x != nil {
		return x.Bitrate
	}
	return ""
}

func (x *FfmpegArgs) GetFaststart() bool {
	if x != nil {
		return x.Faststart
	}
	return false
}

func (x *FfmpegArgs) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

func (x *FfmpegArgs) GetRawArgs() []string {
	if x != nil {
		return x.RawArgs
	}
	return nil
}

// A single progress sample parsed from ffmpeg's "-progress pipe:1 -nostats".
type Progress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Elapsed time (seconds) as reported by ffmpeg.
	Time float64 `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	// Frames processed so far.
	Frame int64 `protobuf:"varint,2,opt,name=frame,proto3" json:"frame,omitempty"`
	// Frames decoded per second.
	Fps float64 `protobuf:"fixed64,3,opt,name=fps,proto3" json:"fps,omitempty"`
	// Overall bitrate, kbit/s.
	Bitrate float64 `protobuf:"fixed64,4,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	// Speed multiplier (e.g. 0.05 for 5% of realtime).
	Speed float64 `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`
	// Output media time in microseconds.
	OutTimeUs int64 `protobuf:"varint,6,opt,name=out_time_us,json=outTimeUs,proto3" json:"out_time_us,omitempty"`
	// Bytes written so far.
	TotalSize int64 `protobuf:"varint,7,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// Frames dropped.
	DropFrames int32 `protobuf:"varint,8,opt,name=drop_frames,json=dropFrames,proto3" json:"drop_frames,omitempty"`
	// Frames duplicated.
	DupFrames int32 `protobuf:"varint,9,opt,name=dup_frames,json=dupFrames,proto3" json:"dup_frames,omitempty"`
	// Parsed "out_time" string as seconds (e.g. "00:00:24.47" -> 24.47).
	OutputTime float64 `protobuf:"fixed64,10,opt,name=output_time,json=outputTime,proto3" json:"output_time,omitempty"`
	// Every raw key/value pair from the ffmpeg sample, verbatim.
	Fields map[string]string `protobuf:"bytes,11,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Completion fraction in [0.0, 1.0] (capped at 1.0): the input's out_time
	// divided by its total duration (as probed at start). Zero when the input
	// has no known duration (e.g. live/RTP streams) — in which case consumers
	// should treat the value as "undetermined" and rely on the raw fields
	// (out_time_us / out_time) instead.
	Percent       float64 `protobuf:"fixed64,12,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_proto_ffrun_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffrun_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_proto_ffrun_proto_rawDescGZIP(), []int{6}
}

func (x *Progress) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Progress) GetFrame() int64 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *Progress) GetFps() float64 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *Progress) GetBitrate() float64 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *Progress) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Progress) GetOutTimeUs() int64 {
	if x != nil {
		return x.OutTimeUs
	}
	return 0
}

func (x *Progress) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *Progress) GetDropFrames() int32 {
	if x != nil {
		return x.DropFrames
	}
	return 0
}

func (x *Progress) GetDupFrames() int32 {
	if x != nil {
		return x.DupFrames
	}
	return 0
}

func (x *Progress) GetOutputTime() float64 {
	if x != nil {
		return x.OutputTime
	}
	return 0
}

func (x *Progress) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Progress) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

// A terminal report of the run, set on the last event.
type FfmpegResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when ffmpeg exited 0.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Raw process exit code.
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// The configured output file (echoed).
	Output string `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	// stderr tail when the run failed (last ~4KB), empty on success.
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// Number of progress samples delivered.
	ProgressEvents int64 `protobuf:"varint,5,opt,name=progress_events,json=progressEvents,proto3" json:"progress_events,omitempty"`
	// Highest fps observed.
	MaxFps float64 `protobuf:"fixed64,6,opt,name=max_fps,json=maxFps,proto3" json:"max_fps,omitempty"`
	// Last "frame" value seen.
	LastFrame     int64 `protobuf:"varint,7,opt,name=last_frame,json=lastFrame,proto3" json:"last_frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FfmpegResult) Reset() {
	*x = FfmpegResult{}
	mi := &file_proto_ffrun_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FfmpegResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FfmpegResult) ProtoMessage() {}

func (x *FfmpegResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffrun_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FfmpegResult.ProtoReflect.Descriptor instead.
func (*FfmpegResult) Descriptor() ([]byte, []int) {
	return file_proto_ffrun_proto_rawDescGZIP(), []int{7}
}

func (x *FfmpegResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FfmpegResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *FfmpegResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *FfmpegResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FfmpegResult) GetProgressEvents() int64 {
	if x != nil {
		return x.ProgressEvents
	}
	return 0
}

func (x *FfmpegResult) GetMaxFps() float64 {
	if x != nil {
		return x.MaxFps
	}
	return 0
}

func (x *FfmpegResult) GetLastFrame() int64 {
	if x != nil {
		return x.LastFrame
	}
	return 0
}

// Event is delivered to the callback registered via FfmpegRun.OnUpdate.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one of the following is set on any given event.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*Event_State
	//	*Event_Progress
	Kind isEvent_Kind `protobuf_oneof:"kind"`
	// Populated only on the terminal (state==COMPLETED/FAILED) event.
	Result        *FfmpegResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_ffrun_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ffrun_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_ffrun_proto_rawDescGZIP(), []int{8}
}

func (x *Event) GetKind() isEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Event) GetState() FfmpegState {
	if x != nil {
		if x, ok := x.Kind.(*Event_State); ok {
			return x.State
		}
	}
	return FfmpegState_FFMPEG_STATE_UNSPECIFIED
}

func (x *Event) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Kind.(*Event_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *Event) GetResult() *FfmpegResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type isEvent_Kind interface {
	isEvent_Kind()
}

type Event_State struct {
	State FfmpegState `protobuf:"varint,1,opt,name=state,proto3,enum=cloudfra.ffrun.FfmpegState,oneof"`
}

type Event_Progress struct {
	Progress *Progress `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

func (*Event_State) isEvent_Kind() {}

func (*Event_Progress) isEvent_Kind() {}

var File_proto_ffrun_proto protoreflect.FileDescriptor

const file_proto_ffrun_proto_rawDesc = "" +
	"\n" +
	"\x11proto/ffrun.proto\x12\x0ecloudfra.ffrun\"\xd3\x01\n" +
	"\x04Args\x129\n" +
	"\x19use_external_if_available\x18\x01 \x01(\bR\x16useExternalIfAvailable\x12#\n" +
	"\rffmpeg_binary\x18\x02 \x01(\fR\fffmpegBinary\x12%\n" +
	"\x0effprobe_binary\x18\x03 \x01(\fR\rffprobeBinary\x12\x19\n" +
	"\bwork_dir\x18\x04 \x01(\tR\aworkDir\x12)\n" +
	"\x10disable_download\x18\x05 \x01(\bR\x0fdisableDownload\"\x92\x02\n" +
	"\vFfProbeArgs\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12\x1f\n" +
	"\vshow_format\x18\x02 \x01(\bR\n" +
	"showFormat\x12!\n" +
	"\fshow_streams\x18\x03 \x01(\bR\vshowStreams\x12#\n" +
	"\rshow_chapters\x18\x04 \x01(\bR\fshowChapters\x12\x1f\n" +
	"\vshow_frames\x18\x05 \x01(\bR\n" +
	"showFrames\x12%\n" +
	"\x0eselect_streams\x18\x06 \x01(\tR\rselectStreams\x12!\n" +
	"\fprint_format\x18\a \x01(\tR\vprintFormat\x12\x19\n" +
	"\braw_args\x18\b \x03(\tR\arawArgs\"\xe5\x05\n" +
	"\rFfProbeStream\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\x12\x1d\n" +
	"\n" +
	"codec_name\x18\x02 \x01(\tR\tcodecName\x12&\n" +
	"\x0fcodec_long_name\x18\x03 \x01(\tR\rcodecLongName\x12\x18\n" +
	"\aprofile\x18\x04 \x01(\tR\aprofile\x12\x1d\n" +
	"\n" +
	"codec_type\x18\x05 \x01(\tR\tcodecType\x12\x1b\n" +
	"\tcodec_tag\x18\x06 \x01(\tR\bcodecTag\x12(\n" +
	"\x10codec_tag_string\x18\a \x01(\tR\x0ecodecTagString\x12\x19\n" +
	"\bbit_rate\x18\b \x01(\x03R\abitRate\x12\x14\n" +
	"\x05width\x18\t \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\n" +
	" \x01(\x05R\x06height\x12\x17\n" +
	"\apix_fmt\x18\v \x01(\tR\x06pixFmt\x12\x14\n" +
	"\x05level\x18\f \x01(\tR\x05level\x12 \n" +
	"\fr_frame_rate\x18\r \x01(\x01R\n" +
	"rFrameRate\x12$\n" +
	"\x0eavg_frame_rate\x18\x0e \x01(\x01R\favgFrameRate\x12\x1f\n" +
	"\vsample_rate\x18\x0f \x01(\x03R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x10 \x01(\x05R\bchannels\x12%\n" +
	"\x0echannel_layout\x18\x11 \x01(\tR\rchannelLayout\x12&\n" +
	"\x0fbits_per_sample\x18\x12 \x01(\x05R\rbitsPerSample\x12\x1a\n" +
	"\bsettings\x18\x13 \x01(\tR\bsettings\x12;\n" +
	"\x04tags\x18\x14 \x03(\v2'.cloudfra.ffrun.FfProbeStream.TagsEntryR\x04tags\x12\x19\n" +
	"\braw_json\x18\x15 \x01(\tR\arawJson\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfa\x02\n" +
	"\rFfProbeFormat\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\x12\x1f\n" +
	"\vformat_name\x18\x03 \x01(\tR\n" +
	"formatName\x12(\n" +
	"\x10format_long_name\x18\x04 \x01(\tR\x0eformatLongName\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x01R\tstartTime\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x01R\bduration\x12\x19\n" +
	"\bbit_rate\x18\a \x01(\x03R\abitRate\x12;\n" +
	"\x04tags\x18\b \x03(\v2'.cloudfra.ffrun.FfProbeFormat.TagsEntryR\x04tags\x12\x19\n" +
	"\braw_json\x18\t \x01(\tR\arawJson\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x01\n" +
	"\rFfProbeResult\x125\n" +
	"\x06format\x18\x01 \x01(\v2\x1d.cloudfra.ffrun.FfProbeFormatR\x06format\x127\n" +
	"\astreams\x18\x02 \x03(\v2\x1d.cloudfra.ffrun.FfProbeStreamR\astreams\x12\x19\n" +
	"\braw_json\x18\x03 \x01(\tR\arawJson\"\x99\x02\n" +
	"\n" +
	"FfmpegArgs\x12\x16\n" +
	"\x06inputs\x18\x01 \x03(\tR\x06inputs\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x1f\n" +
	"\vvideo_codec\x18\x03 \x01(\tR\n" +
	"videoCodec\x12\x1f\n" +
	"\vaudio_codec\x18\x04 \x01(\tR\n" +
	"audioCodec\x12\x10\n" +
	"\x03crf\x18\x05 \x01(\x05R\x03crf\x12\x16\n" +
	"\x06preset\x18\x06 \x01(\tR\x06preset\x12\x18\n" +
	"\abitrate\x18\a \x01(\tR\abitrate\x12\x1c\n" +
	"\tfaststart\x18\b \x01(\bR\tfaststart\x12\x1c\n" +
	"\toverwrite\x18\t \x01(\bR\toverwrite\x12\x19\n" +
	"\braw_args\x18\n" +
	" \x03(\tR\arawArgs\"\xa9\x03\n" +
	"\bProgress\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x01R\x04time\x12\x14\n" +
	"\x05frame\x18\x02 \x01(\x03R\x05frame\x12\x10\n" +
	"\x03fps\x18\x03 \x01(\x01R\x03fps\x12\x18\n" +
	"\abitrate\x18\x04 \x01(\x01R\abitrate\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x01R\x05speed\x12\x1e\n" +
	"\vout_time_us\x18\x06 \x01(\x03R\toutTimeUs\x12\x1d\n" +
	"\n" +
	"total_size\x18\a \x01(\x03R\ttotalSize\x12\x1f\n" +
	"\vdrop_frames\x18\b \x01(\x05R\n" +
	"dropFrames\x12\x1d\n" +
	"\n" +
	"dup_frames\x18\t \x01(\x05R\tdupFrames\x12\x1f\n" +
	"\voutput_time\x18\n" +
	" \x01(\x01R\n" +
	"outputTime\x12<\n" +
	"\x06fields\x18\v \x03(\v2$.cloudfra.ffrun.Progress.FieldsEntryR\x06fields\x12\x18\n" +
	"\apercent\x18\f \x01(\x01R\apercent\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x01\n" +
	"\fFfmpegResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12'\n" +
	"\x0fprogress_events\x18\x05 \x01(\x03R\x0eprogressEvents\x12\x17\n" +
	"\amax_fps\x18\x06 \x01(\x01R\x06maxFps\x12\x1d\n" +
	"\n" +
	"last_frame\x18\a \x01(\x03R\tlastFrame\"\xb2\x01\n" +
	"\x05Event\x123\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.cloudfra.ffrun.FfmpegStateH\x00R\x05state\x126\n" +
	"\bprogress\x18\x02 \x01(\v2\x18.cloudfra.ffrun.ProgressH\x00R\bprogress\x124\n" +
	"\x06result\x18\x03 \x01(\v2\x1c.cloudfra.ffrun.FfmpegResultR\x06resultB\x06\n" +
	"\x04kind*\x95\x01\n" +
	"\vFfmpegState\x12\x1c\n" +
	"\x18FFMPEG_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15FFMPEG_STATE_STARTING\x10\x01\x12\x18\n" +
	"\x14FFMPEG_STATE_RUNNING\x10\x02\x12\x1a\n" +
	"\x16FFMPEG_STATE_COMPLETED\x10\x03\x12\x17\n" +
	"\x13FFMPEG_STATE_FAILED\x10\x04B'Z%github.com/cloudfra/ffmpegembed/protob\x06proto3"

var (
	file_proto_ffrun_proto_rawDescOnce sync.Once
	file_proto_ffrun_proto_rawDescData []byte
)

func file_proto_ffrun_proto_rawDescGZIP() []byte {
	file_proto_ffrun_proto_rawDescOnce.Do(func() {
		file_proto_ffrun_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ffrun_proto_rawDesc), len(file_proto_ffrun_proto_rawDesc)))
	})
	return file_proto_ffrun_proto_rawDescData
}

var file_proto_ffrun_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ffrun_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_ffrun_proto_goTypes = []any{
	(FfmpegState)(0),      // 0: cloudfra.ffrun.FfmpegState
	(*Args)(nil),          // 1: cloudfra.ffrun.Args
	(*FfProbeArgs)(nil),   // 2: cloudfra.ffrun.FfProbeArgs
	(*FfProbeStream)(nil), // 3: cloudfra.ffrun.FfProbeStream
	(*FfProbeFormat)(nil), // 4: cloudfra.ffrun.FfProbeFormat
	(*FfProbeResult)(nil), // 5: cloudfra.ffrun.FfProbeResult
	(*FfmpegArgs)(nil),    // 6: cloudfra.ffrun.FfmpegArgs
	(*Progress)(nil),      // 7: cloudfra.ffrun.Progress
	(*FfmpegResult)(nil),  // 8: cloudfra.ffrun.FfmpegResult
	(*Event)(nil),         // 9: cloudfra.ffrun.Event
	nil,                   // 10: cloudfra.ffrun.FfProbeStream.TagsEntry
	nil,                   // 11: cloudfra.ffrun.FfProbeFormat.TagsEntry
	nil,                   // 12: cloudfra.ffrun.Progress.FieldsEntry
}
var file_proto_ffrun_proto_depIdxs = []int32{
	10, // 0: cloudfra.ffrun.FfProbeStream.tags:type_name -> cloudfra.ffrun.FfProbeStream.TagsEntry
	11, // 1: cloudfra.ffrun.FfProbeFormat.tags:type_name -> cloudfra.ffrun.FfProbeFormat.TagsEntry
	4,  // 2: cloudfra.ffrun.FfProbeResult.format:type_name -> cloudfra.ffrun.FfProbeFormat
	3,  // 3: cloudfra.ffrun.FfProbeResult.streams:type_name -> cloudfra.ffrun.FfProbeStream
	12, // 4: cloudfra.ffrun.Progress.fields:type_name -> cloudfra.ffrun.Progress.FieldsEntry
	0,  // 5: cloudfra.ffrun.Event.state:type_name -> cloudfra.ffrun.FfmpegState
	7,  // 6: cloudfra.ffrun.Event.progress:type_name -> cloudfra.ffrun.Progress
	8,  // 7: cloudfra.ffrun.Event.result:type_name -> cloudfra.ffrun.FfmpegResult
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_ffrun_proto_init() }
func file_proto_ffrun_proto_init() {
	if File_proto_ffrun_proto != nil {
		return
	}
	file_proto_ffrun_proto_msgTypes[8].OneofWrappers = []any{
		(*Event_State)(nil),
		(*Event_Progress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ffrun_proto_rawDesc), len(file_proto_ffrun_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ffrun_proto_goTypes,
		DependencyIndexes: file_proto_ffrun_proto_depIdxs,
		EnumInfos:         file_proto_ffrun_proto_enumTypes,
		MessageInfos:      file_proto_ffrun_proto_msgTypes,
	}.Build()
	File_proto_ffrun_proto = out.File
	file_proto_ffrun_proto_goTypes = nil
	file_proto_ffrun_proto_depIdxs = nil
}
